article: [
	{
		subTitle: "Why does every moment of the day have its own yoga",
		paragraph: "The presence or absence of sunlight are two factors that for a very long part of our evolution have been decisive in establishing the rhythms of our life; this is still the case today, obviously, even if the advent of electricity and the possibility of brightly lighting our homes at any time of the day have substantially changed the experience we have of the sleep/wake alternation. However, it remains implicit in our nature that we feel more active in the morning and tired in the evening, after a long day spent between work and various commitments. Our body, in fact, follows the so-called 'circadian rhythms', i.e. biological cycles that are based on sunlight and which influence a vast range of physiological processes, including sleep, digestion and metabolism. Well, yoga and Ayurveda can be used to help us harmonize circadian rhythms and improve our overall health. And just like the sun reaches that its peak at midday and then sets again towards the evening, the practice of yoga should maintain the same 'energetic' logic. In fact, every moment of the day has a different energy, just think of how we feel when we wake up in the morning, or the sensations we feel when we observe a sunrise or, on the contrary, how we feel when we observe a sunset. The morning brings with it the freshness, dynamism, effervescence and curiosity of the new, for this reason, in these hours of the day, the ideal would be to dedicate ourselves to an energizing yoga practice that provides us with a good boost to do the tasks of the day with the right dose of calm, concentration and tranquility. Likewise, as the hours of the day pass, and the intensity of the sun decreases, our energy reserves are also consumed, so that, when we reach the evening, we will need a gentle practice like a sunset to help us release the stress and tensions accumulated during the day, and contribute to having a regenerating and deep sleep. For this reason there are different yoga practices that adapt to different moments of the day, such as the Sun Salutation, ideal to do in the morning, and the Moon Salutation, ideal to do in the evening. (We'll talk about both in a bit.) As for Ayurveda, it is based on the theory that the three doshas (Vata, Pitta and Kapha) regulate the functioning of our body and mind. Each dosha has its own unique qualities and its activity is greater at certain times of the day. Let's look at them one at a time"
	},
	{
		subTitle: "From 2am to 6am and from 2pm to 6p",
		paragraph: "In this time slot the Vata dosha predominates, which regulates the movement and activity of the nervous system. This element is associated with mental activity and thought, therefore making these hours of the day particularly favorable for the practice of yoga and meditation. At this time, generally, the quality of the mind is purer, since there are no thoughts of the day, and the energy is more conductive to inducing the state of meditation. It is also for this reason that if you go to an Ashram in India, you will most likely have to wake up at 5 in the morning to meditate. "
	},
	{
		subTitle: "From 10am to 2pm and from 10pm to 2am",
		paragraph: "In this time slot, the Pitta dosha predominates, which regulates metabolism and digestion. This time slot is particularly beneficial for working on the digestive fire, considering that it is the moment of greatest activation. Sequences to improve digestion are indicated, but only during the day; in the evening, however, by putting additional embers on the fire, you risk tossing and turning into bed all night. It is also for this reason that, during the evening time slot in which this element predominates, not only are all energizing practices not recommended, but it would also be preferable to avoid intense physical activity"
	},
	{
		subTitle: "From 6am to 10am and between 6pm and 10pm",
		paragraph: "In this time slot the Kapha dosha predominates, which regulates the structure of the body and the immune system. In this phase, the morning is ideal for doing intense exercise, even in the gym or for a run, while in the evening, although it is true that this dosha wants to make us move, we still need to consider the biological clock and therefore move in moderation, otherwise, as in the case of the Pitta dosha, you risk tossing and returning to bed all night"
	},
	{
		subTitle: "Yoga before or after meals",
		paragraph: "Another relevant indication concerns the amount of time that should pass between the last meal and the start of the practice. In this sense it is important to remember that ideally at least three hours should pass after meals before unrolling the mat, even if, in some cases, you can end up eating something, such as a banana or a smoothie, even half an hour before if perhaps it is we don't eat all day and we need energy to sustain the practice. However, there are many factors involved, from what and how we choose to eat (it is not the same thing to eat rice and vegetables or a pizza, and do it calmly or in a hurry), to what type of practice you are going to carry out, whether more or less meditative, for example, down to one's characteristics and metabolism. For these reasons, our advice is to always listen to the body's signals, learning to interpret what it tells us, starting from what you feel you need to eat for dinner, to when you feel it is time to unroll the mat, to the type of practice he needs at that moment"
	},
]